### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mstieber**
Updated ReadMe 'Caveats' to call out incompatibility with Shared pages in Rally.

### CODE REVIEW

**Review by abrockett — APPROVED** [review]
Looks good!

**Comment by kcorkan** [comment]
Thanks Mike!  I definitely think the added caveats are good.  I'm curious, what issues we see associated with using a shared page using this app?   Also, this is forked from kcorkan, which I'm not sure anyone uses other than me.  Should we instead merge this into RallyCommunity?  https://github.com/RallyCommunity/custom-grid-with-deep-export

**Comment by mstieber** [comment]
My intent was to make the change for RallyCommunity, sorry.

from support and a link to the COmmunity post:
'It seems that specific views (i.e column setup) in apps deployed into custom pages are kept personal and not shared with others, despite that the custom page and the deployed app are shared.'

https://community.broadcom.com/enterprisesoftware/communities/community-home/digestviewer/viewthread?GroupId=2437&MessageKey=fccc35c0-e3c5-4721-9506-eb071bde2388&CommunityKey=f303f769-8d4c-44d9-924c-3845bba6444e&tab=digestviewer&ReturnUrl=%2fenterprisesoftware%2fcommunities%2fcommunity-home%2fdigestviewer%3fcommunitykey%3df303f769-8d4c-44d9-924c-3845bba6444e%26tab%3ddigestviewer

**Comment by kcorkan** [comment]
No worries at all.  Thanks for the link -- that is helpful.  This looks good to me!

**Comment by mstieber** [comment]
Closing in favor of this PR instead
https://github.com/RallyCommunity/custom-grid-with-deep-export/pull/26

**Pull request closed without merging**
